### ISSUE TITLE
inTeams() check does not work with mobile app

### ISSUE THREAD

**Issue by glapointe** [wictorwilen/msteams-react-base-component#1]
The inTeams() method located here, https://github.com/wictorwilen/msteams-react-base-component/blob/master/src/index.tsx, doesn't work if you're in the mobile app. Checking whether you're in an iframe probably isn't the best approach regardless as there are cases when the app you're hosting may also be hosted elsewhere in an iframe.

**Comment by wictorwilen** [comment]
@glapointe - aware of this issue, and this method will be deprecated in future versions (actually not used in the new preview of the generator when you use SSO tabs)

**Comment by wictorwilen** [comment]
@glapointe - I'm looking into replacing the method with a solution like this: https://github.com/OfficeDev/microsoft-teams-library-js/issues/272#issuecomment-600739495

**Comment by wictorwilen** [comment]
Issue fixed with new method in 2.1.0 (https://github.com/wictorwilen/msteams-react-base-component/commit/93b26eefac5b77b7549a3f0bb826ec82b610224b)
