### ISSUE TITLE
Can't use react-router-dom + history.push

### ISSUE THREAD

**Issue by DaleyKD** [wictorwilen/msteams-react-base-component#13]
When trying to use `const history = useHistory();` along with `history.push("/newUrl");`, it does a great job of changing the URL and loading the next react component.  However, the base class stuff doesn't seem to "carry over."  The main symptom of this for us is that the theme change handler doesn't fire on the second page.

https://codesandbox.io/s/wonderful-shannon-63rdw?file=/src/App.js

While I can't test the codesandbox in actual Teams, it should give you an idea of what I'm trying to describe. I'm also on vacation right now, so this is a SUPER fast write-up.  I've done about an hour of initial debugging with our code to prove that none of the events fire.

**Comment by wictorwilen** [comment]
(vacation here as well :-)) - but a quick fix could be to do `history.push("/newUrl?theme=" + theme)`

**Comment by DaleyKD** [comment]
OK. I think I figured it out.  It's not you, it's me, but perhaps something that could be documented for us that aren't react whizzes.

https://codesandbox.io/s/mystifying-goldberg-1nj6h?file=/src/App.js

The `useTeams();` hook needs to be in a functional component that's inside of the `<BrowserRouter />`.  What I ended up doing was just breaking out some of my inner elements (controls) from `MyApp` and putting them into `MyInnerApp` along with the `useTeams` hook, etc.  That seems? to have fixed the issue.

Sorry for the false alarm.  Enjoy your vacation.

**Comment by DaleyKD** [comment]
Well, I may have lied.  So ignore my previous statement.  Let me try this again.

The actual cause for all of the theme problem was that ** I ** had:

``` jsx
    React.useEffect(() => {
        if (context) {
            if (context.theme && context.theme !== initialTheme) {
                updateAllThemes(context.theme);
            }
        }

        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [context, initialTheme]);
```

This snippet did something similar to where you set the theme based on `context.theme`. This is the `context` from `microsoftTeams.getContext`.  _(My `updateAllThemes` needs to load up my own stylesheets that I use to get Telerik Kendo to look similar to react-northstar.)_

What is currently happening is that my `useEffect` is called after a theme update because (I assume) `context` is "loaded" (or something) for this render (after the `history.push()`).  The **problem** is that `context` is stale.  It didn't reload after the user changed the theme. For today, I can work around this if we can make a change. (Forgive me for not knowing how to do a PR. This is something I need to learn early in 2021.)

If I give the option for setting my themeHandler when using the `useTeams` hook, everything works great.

``` jsx
export function useTeams(options?: { initialTheme?: string, setThemeHandler?: (theme?: string) => void }): [

...

const overrideThemeHandler = options?.setThemeHandler ? options.setThemeHandler : themeChangeHandler;

...

        if (initialTheme) {
            overrideThemeHandler(initialTheme);
        }
        const isInTeams = checkInTeams();
        if (isInTeams) {
            microsoftTeams.initialize(() => {
                microsoftTeams.getContext(context => {
                    batchedUpdates(() => {
                        setInTeams(true);
                        setContext(context);
                        setFullScreen(context.isFullScreen);
                    });
                    overrideThemeHandler(context.theme);
```

Then I can just pass mine in: 

``` jsx
const [{ inTeams, theme, context }, { setTheme }] = useTeams({ initialTheme: initialTheme, setThemeHandler: updateAllThemes });
```

I **still** use your `setTheme` (aka `themeChangeHandler`) in my `updateAllThemes`.

Just my two cents.

**Comment by DaleyKD** [comment]
This is a polite bump.  We're nearing the end of our programming increment, and are getting close to release. I need to know if I'm going to have to fork this temporarily.

I know that sounds rude, and I don't mean for it to be. I just have an open bug on my backlog for this.

Thanks again for everything!

**Comment by wictorwilen** [comment]
Added a custom theme handler as suggested in #18
