### ISSUE TITLE
Missing Context Properties (3.0.2)

### ISSUE THREAD

**Issue by webdes03** [wictorwilen/msteams-react-base-component#17]
Tested with 3.0.2, there's a number of context properties that are missing when running a tab in multi window mode.

When opening natively within Teams the following context properties are present:

locale
theme
entityId
subEntityId
isFullScreen
sessionId
chatId
meetingId
hostClientType
tenantSKU
jsonTabUrl
userLicenseType
appSessionId
isMultiWindow
appIconPosition
frameContext
isTeamArchived
teamType
userTeamRole
channelRelativeUrl
channelId
channelName
channelType
defaultOneNoteSectionId
groupId
teamId
teamName
teamSiteUrl
teamSiteDomain
teamSitePath
ringId
tid
loginHint
upn
userPrincipalName
userObjectId

When opening in multi-window mode, only this smaller subset of context properties are present:

hostClientType
frameContext,
loginHint
tid
upn
userObjectId
userPrincipalName
theme
locale
ringId
meetingId
isMultiWindow
glassjarBaseUrl
chatId
sessionId
channelId
groupId
teamId
teamSiteUrl
teamSiteDomain
teamSitePath
sharepoint
subEntityId
entityId

**Comment by wictorwilen** [comment]
Thanks for reporting this. However the context properties are retrieved from the Microsoft Teams JS SDK, and you should report any issues with in that repo: https://github.com/OfficeDev/microsoft-teams-library-js
