### ISSUE TITLE
Uncompatible with @fluentui/react-northstar@^0.50.0

### ISSUE THREAD

**Issue by kevinprakasa** [wictorwilen/msteams-react-base-component#4]
This happened to me when I was trying to use some icons from react-northstar@0.50.0 and later version. And then I upgraded react-northstar package from 0.49.0 and got this error. The context was me trying to build MS Teams app with yeoman generator.

![Screen Shot 2020-07-28 at 07 25 55](https://user-images.githubusercontent.com/23476276/88605406-011b4600-d0a4-11ea-91db-563fbc61535b.png)

I think this issue was raised because there was a slightly changes in how react-northstar@0.50.0 and later versions export file.

[https://github.com/microsoft/fluentui/blob/5f80b4d72d88d16bb33af1a33817e199fb61fadf/packages/fluentui/react-northstar/src/index.ts#L10](https://github.com/microsoft/fluentui/blob/5f80b4d72d88d16bb33af1a33817e199fb61fadf/packages/fluentui/react-northstar/src/index.ts#L10)

**Comment by wictorwilen** [comment]
This is now fixed in the latest preview: bc1bfac5bbc266570ed6c6a66014b035d9a51a3c
