### ISSUE TITLE
Main Page Usage shows pageFontSize() and entityId, but those don't exist

### ISSUE THREAD

**Issue by DaleyKD** [wictorwilen/msteams-react-base-component#6]
ALL of this is new to me (React, northstar, etc), but I noticed that version 2.1.0 fontSize stuff.

However, your usage in README.md still uses
```
this.setState({
  fontSize: this.pageFontSize()
});
```

I also see use of `<Text content={this.state.entityId} />`, but entityId doesn't exist.

Are these no longer valid uses?  Why the removal?

**Comment by wictorwilen** [comment]
You're correct. The README file was not correctly updated after this was removed in `2.1.0`. This is fixed for upcoming releases.
