### ISSUE TITLE
Preview Branch: Consider Exporting getQueryVariable 

### ISSUE THREAD

**Issue by DaleyKD** [wictorwilen/msteams-react-base-component#7]
In the current version, since we can inherit from your class, we can use `getQueryVariable`. In the upcoming preview version, it looks like you're not exporting it. It'd be nice to be able to use that function in case we need it.

**Comment by wictorwilen** [comment]
Great suggestion. I'll ensure it's exported

**Comment by wictorwilen** [comment]
Added to #8
